# Generated by Django 5.2 on 2025-04-03 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
