# Generated by Django 5.2 on 2025-04-04 06:15

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('study_groups', '0004_notes_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='study_groups.study_group'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='study_groups.study_group'),
        ),
    ]
