# Generated by Django 5.2 on 2025-04-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations_and_group_matching', '0002_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnicalConstraint',
            new_name='Courses',
        ),
    ]
