# Generated by Django 5.2 on 2025-04-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations_and_group_matching', '0004_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
