# Generated by Django 5.2 on 2025-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0002_rename_achievement_achievement_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogress',
            name='study_time',
            field=models.IntegerField(help_text='Total study time in Hours'),
        ),
    ]
